(ert-deftest dotpair-test ()
  (should (equal '(1 2 3) '(1 . (2 . (3 . nil)))))
  (let ((mapping '((a . "aaa")
                   (b . "bbb")
                   (c . "ccc"))))
    (should (equal '(a . "aaa") (car mapping)))
    (should (equal '((b . "bbb") (c . "ccc")) (cdr mapping)))
    (should (equal '(a . "aaa") (assq 'a mapping)))
    (should (equal 'a (car (assq 'a mapping))))
    (should (string= "aaa" (cdr (assq 'a mapping))))))
