name: test

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 28.1
          - 28.2
          - snapshot
        ignore_warnings:
          - true
        include:
          - emacs_version: snapshot
            ignore_warnings: false
    steps:
    - uses: actions/checkout@v3
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - name: cask install
      run: make init-cask
    - name: package-install
      run: make install
    - name: lisp-test
      run: make test
    - name: byte-compile
      run: make compile
